### ISSUE TITLE
en_US.lang missing

### ISSUE THREAD

**Issue by PCobald** [Darkhax-Minecraft/Ore-Stages#12]
Please create the folder assets\orestage to the folder .\assets and past the en_US.lang file in there.

for example ...
[assets.zip](https://github.com/Darkhax-Minecraft/Ore-Stages/files/1863729/assets.zip)

**Comment by jaredlll08** [comment]
Why? This mod has no localization, it doesn't need it.

**Comment by PCobald** [comment]
The ForgeLoader means . . .

[m> 
[15:26:29] [Server thread/WARN] [FML]: Missing English translation for gamestages: assets/gamestages/lang/en_us.lang
[m> 
[15:26:29] [Server thread/WARN] [FML]: Missing English translation for orestages: assets/orestages/lang/en_us.lang

**Comment by PCobald** [comment]
that's both

**Comment by darkhax** [comment]
Thank you for reporting this issue, I will look into when I have a chance. Hopefully before the end of the long weekend.

**Comment by darkhax** [comment]
Fixed in https://github.com/Darkhax-Minecraft/Ore-Stages/commit/115937781236b60c9612adc749283c0cc516ea73

**Comment by PCobald** [comment]
thanks vm
