### ISSUE TITLE
Ore Staging colour and waila issue.

### ISSUE THREAD

**Issue by Ryzelf** [Darkhax-Minecraft/Ore-Stages#14]
While Disguising anything as any grass like foliage block it shows with no colour and shows wrong on WAILA/WAWLA
![2018-04-10_18 19 41](https://user-images.githubusercontent.com/36670226/38572937-83a4db02-3cec-11e8-8dbd-4cd0cd0fc42d.png)

**Comment by darkhax** [comment]
OreStages does not support block colours unfortunately. This means things like grass, tall grass, leaves, ferns, sugar cane, water and so on will not work. At this point I don't know if it is realistic to fix this issue, but I will try.
