### ISSUE TITLE
Game Error Loop

### ISSUE THREAD

**Issue by tkxyooj** [Darkhax-Minecraft/Ore-Stages#16]
I'm creating a modpack with orestages. Loaded all the mods and configurations without any issues. I create a whole new world and within minutes, I am thrown into a loop where the game becomes unplayable. I can't issue commands, I lose inventory, and hotkeys no longer work. The world does not instantly crash as I can move about in the loaded chunks, but that all I can do. Looking into the the logs, I see that orestages runs into a null exception and goes into a loop. It causes the log file to jump in size up to 100+ MB. I was able to copy up the end of the loop and at the end of copy, the same error is looped through. Not sure what the issue could be. I updated to the latest version of gamestages, bookshelf, and forge and still received the same error. Reverting my versions back to before the update and still the same error. Error can be found at this [link](https://github.com/tkxyooj/modpack-issues/blob/master/deathloop).

**Comment by darkhax** [comment]
Can you post the script you are using? This is a case of your script hiding a block as itself, or hiding a block as something else that is hidden by itself.

**Comment by tkxyooj** [comment]
[This ](https://github.com/tkxyooj/RR-custom-scripts/tree/master/scripts)is the repository of the scripts being used. There doesn't look to be looping blocks, but I could be wrong.

**Comment by tkxyooj** [comment]
Re configuring the scripts got to the loops to go away. It was an issue in the script to hide the grass blocks and another line to hide the replacement block. I've come up with a new workaround that fits into the lore of the pack using recipe stages so I took out the line to hide the replacement block. It was odd that this issue only appeared recently, as I was able to use the script up until I decided to update gamestages and orestages. But anyways, the issue is solved.

**Comment by darkhax** [comment]
Thanks for the followup. Could you write me a few lines of script which can be used to reproduce this issue? If I have a way to reproduce the issue I can create some code that will detect these issues and alert the pack maker. I may even be able to write something that allows the hierarchy of restrictions to work as you want.
