### ISSUE TITLE
Reloading Resources from main menu can NPE

### ISSUE THREAD

**Issue by gegy1000** [Darkhax-Minecraft/Ore-Stages#18]
https://github.com/Darkhax-Minecraft/Ore-Stages/blob/3b5e9396dc039c72cfab2e098674271e955ca1a7/src/main/java/net/darkhax/orestages/client/renderer/block/model/BakedModelTiered.java#L55

If client player is null (as it is on the main menu), the code will throw an NPE when calling:
https://github.com/Darkhax-Minecraft/Game-Stages/blob/9fed6009f53a8abea626251c927dd9afcbb03705/src/main/java/net/darkhax/gamestages/GameStageHelper.java#L271-L279

**Comment by darkhax** [comment]
How does someone even reload the resources on the main menu?

**Comment by darkhax** [comment]
I added a check to default to the replacement model if there is no player. You should check to see if this resolved your issue, and if your PR breaks the way I patch models.

**Comment by gegy1000** [comment]
You can change language while on the main menu, which causes a resource reload.
