### ISSUE TITLE
Ores does not hide if TexturePack is applied

### ISSUE THREAD

**Issue by Pirog17000** [Darkhax-Minecraft/Ore-Stages#19]
I'm using Dokucraft and was frustrated about what I'm doing wrong until turned my texturepack off.
Somehow ores are not hidden if resourcepack is active. But with vanilla it does hide the ores.
So.. this is probably a bug.

Oh, also I'm using CTM: https://minecraft.curseforge.com/projects/ctm?gameCategorySlug=mc-mods&projectID=267602

How does it look in game:
without textures:
https://cdn.discordapp.com/attachments/435392929847312392/448833131320180736/unknown.png

with textures:
https://cdn.discordapp.com/attachments/435392929847312392/448833353374760961/unknown.png

**Comment by darkhax** [comment]
Hi there, sorry for the very late response. This should be fixed now. If it's not let me know and I will look into things a bit more.
