### ISSUE TITLE
infinite loop when disguising block as itself and breaking it

### ISSUE THREAD

**Issue by CreepyCre** [Darkhax-Minecraft/Ore-Stages#21]
self explanatory
happens both in creative an survival mode, only when stage is not yet reached

would like to be able to use this so I can deny access to certain crafting stations per stage (as ore stages disables rightclick)

**Comment by darkhax** [comment]
Thank you for the report. This is an unsupported way to use the mod, but I can look into writing something to help fix this for you. I don't have a time frame for that fix though.
