### ISSUE TITLE
Waila show the hidden blocks (With OreStages 2.0.30)

### ISSUE THREAD

**Issue by Fireztonez** [Darkhax-Minecraft/Ore-Stages#23]
With the latest version of OreStages and GameStages, when you look a hidden block, you see what the real block is in Waila, and not the block you see.

I see that problem in my big modpack working on... So I try in a new small pack containing only what I need to test, without any extra, and it still happen.

If I just downgrade GameStages and OreStages to the version 1.xx, everithing is good, waila show the good thing... So I think you need to fix something in OreStages for fix that...

![image](https://user-images.githubusercontent.com/19277301/41936440-300da91e-795b-11e8-8a34-11fb257755c0.png)

Version:
Minecraft 1.12.2
Forge 14.23.4.2713
HWYLA (Waila 1.8.46-B41)
Game Stages 2.0.91
Ore Stages 2.0.30
Crafttweaker2 4.1.9

Fireztonez

**Comment by darkhax** [comment]
Thanks for the report, should now be fixed.

**Comment by Fireztonez** [comment]
Thank's I will try :)

**Comment by Fireztonez** [comment]
Oki, I just install the last alpha version, and the problem is fixed ;)

Thank's

**Comment by darkhax** [comment]
Thanks for confirming the fix :)
