### ISSUE TITLE
Un-masked ores breaking like mask on multiplayer.

### ISSUE THREAD

**Issue by SuperKael** [Darkhax-Minecraft/Ore-Stages#24]
On multiplayer, ores that were originally locked but have since been unlocked have the mining speed and supposed mining level of the block they were previously hidden as. For example, diamond ore (that was previously masked as stone) breaks as fast as stone did using a stone pickaxe. However, it has to be 'broken' multiple times before it actually breaks, and when it does nothing drops (because a stone pickaxe should not be able to mine diamond ore). I am pretty sure that has something to do with playing on a dedicated server.

**Comment by darkhax** [comment]
Are you using the latest version? I can not reproduce this error using 2.0.31.
