### ISSUE TITLE
Batching Chunks

### ISSUE THREAD

**Issue by NillerMedDild** [Darkhax-Minecraft/Ore-Stages#25]
Hey!

I'm having an issue with a persistent on world-load crash, that seems to stem from the rendering of orestages blocks(?).

Crashlog: https://hastebin.com/ivuyifequm.coffeescript

Erroring Script: https://hastebin.com/cilejitede.cs
Working Script, no crash, # added to line 64 and 65: 
https://hastebin.com/abolemideh.cs

`materials.gold.ore` is `<contenttweaker:ore_gold>`
and the same goes for most other materials.metal.ore items.

Do you have any idea what could be causing this?

**Comment by darkhax** [comment]
This probably isn't OreStages. I am just redirecting the model to another vanilla one. It is likely an issue with `materials.gold.ore` being empty/null/invalid.

CodeChickenLib, Architecture, BetterFoliage, ContentTweaker should all be looked at as well
