### ISSUE TITLE
Some blocks fail to hide

### ISSUE THREAD

**Issue by UnlimatedStone9** [Darkhax-Minecraft/Ore-Stages#26]
I don't know why but some blocks fail to hide as another, the current ones I have discovered are just the vanilla leaves failing to hide as oak leaves until the morevanillawood stage is reached, I believe this may happen with Modded leaf types too but haven't tested yet, is this a problem with the blocks transparency?

**Comment by UnlimatedStone9** [comment]
I also noticed incompatibility with better foliage failing to render logs correctly when rounded logs is enabled, the drops and other functions are correct however they are visually still their original wood

**Comment by darkhax** [comment]
With vanilla leaves, you have to make sure all the stats are being hidden. With better foliage that seems like a conflict with model loading which I can not resolve.
