### ISSUE TITLE
Crashing when Going into the F3 menu

### ISSUE THREAD

**Issue by cavinnhobbes** [Darkhax-Minecraft/Ore-Stages#27]
After creating some orestage enabled scripts, I found that after doing so, pressing F3 just instantly crashed the game with the following crash report: https://pastebin.com/cBxrTDDK
after testing I found that it was not any block in specific, simply any block being staged seems to cause this crash.

**Comment by darkhax** [comment]
Thanks for the report, I've put in a potential fix for this issue. Version 2.0.33 should be live on Curse for you to test out soon.
