### ISSUE TITLE
Disguised blocks don't drop depending on harvestabilty

### ISSUE THREAD

**Issue by tyra314** [Darkhax-Minecraft/Ore-Stages#3]
If you add a replacement for an ore and try to harvest the disguised block, it will drop or not drop based on the harvestability of the ore.

For instance:
```
mods.OreTiers.addReplacement("one", <minecraft:obsidian>, <minecraft:cobblestone>);
```

Trying to break the cobblestone with a wooden pickaxe does actually work, but no cobble is dropped.

**Comment by darkhax** [comment]
Looks like HarvestDropsEvent is not fired when the player can't harvest the block, and forge provides no event to change the harvestable status of a block like we would need.

**Comment by tyra314** [comment]
Have you any ideas how to tackle this issue? I ran in a similar problem in my mod, where I would also need an event. What I think so far, is that [ForgeHoos.canHarvestBlock](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/ForgeHooks.java#L188) would need to trigger a PlayerEvent.HarvestCheck on every code path. At least that would enable me to hook into there...

**Comment by darkhax** [comment]
No, we have not solved the issue yet. I am going to talk with mezz and some other devs tonight and see if we can work something out.
