### ISSUE TITLE
[1.12]crash when pressing f3

### ISSUE THREAD

**Issue by mensreaMC** [Darkhax-Minecraft/Ore-Stages#35]
I get this crash sometimes when pressing f3. Usually it coincides with lag and that's why I'm pressing f3. https://pastebin.com/RZ9gkT3n

**Comment by darkhax** [comment]
This issue was fixed in 2.0.33 and latest Ore Stages is 2.0.37. Could you try out the newer versions and let me know if they resolved this issue?

**Comment by mensreaMC** [comment]
It's fixed. I could have sworn I had the newest version, but if it was an alpha then it was due to twitch.

**Comment by darkhax** [comment]
Thank you for confirming the issue has been fixed.
