### ISSUE TITLE
Hidden Evilcraft dark gem ore masking issue

### ISSUE THREAD

**Issue by Gamertech** [Darkhax-Minecraft/Ore-Stages#36]
MC 1.12.2
GameStages 2.0.110
OreStages 2.0.37
EvilCraft 0.10.64

When hiding Evilcraft's dark gem ore, it's masked correctly, though when hitting it it releases smoke similar to redstone ore for a second, and sometimes reveals itself while the smoke is released when mining it, reverting back to the mask block after a couple of seconds.

Upon mining it, the ore drops dark gems as it would normally instead of the mask block. If you break it with a pick below the required ore mining level, it drops the mask block as intended.

Related note, hidden redstone ore also releases smoke when hitting it, though it doesn't fully reveal itself or drop redstone unlike the dark gems.

**Comment by darkhax** [comment]
Are you using the latest version of EvilCraft? It seems they fixed this issue on October 30th. (0.10.64)

**Comment by Gamertech** [comment]
Yes 0.10.64

**Comment by Darkhax** [comment]
If you still haven't gotten this working, try using something like this for both the normal and smoke states of the block. 

```
mods.orestages.OreStages.addReplacementById("three", "minecraft:nether_wart:*", "minecraft:beetroots");
```
