### ISSUE TITLE
Players happen to mine a hidden block, but gets the hidden item instead of the "mask" item.

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/Ore-Stages#6]
There have been two situations I've heard so far and both make me believe that this is the common situation:

1. Player is walking around the world gathering items.
2. Player breaks a rock, which is masking an ore sample
3. Player ends up getting an ore sample in return, though its hidden as a rock currently
4. Player doesnt even realize it until after when they look in their inventory, since in both situations the player didnt realize they mined it.

I believe this is only on servers, but I'm not sure. Both players have been on servers.

Reference: https://github.com/Darkosto/SevTech-Ages/issues/673

**Comment by justinrusso** [comment]
(For the sake of tracking) It seems like this may be the player right clicking on the item. The hidden item breaks itself on right click and gives its item as a drop.

**Comment by justinrusso** [comment]
Right click seems prevented now, thanks 👍

**Comment by darkhax** [comment]
Nice :D
