### ISSUE TITLE
[Bug] Can't place ores on top of hidden ores

### ISSUE THREAD

**Issue by Zodsmar** [Darkhax-Minecraft/Ore-Stages#7]
If a stage is locked and the ore is hidden. If I go into creative and place lets say iron it turns to stone. But it won't let me place another iron ore on top of the now hidden (Aka stone) ore. I can place ores on any other blocks just not blocks that have been hidden. 
(Hope that makes sense)

**Comment by darkhax** [comment]
Thanks for the report, this will be fixed in the next version that shows up on CurseForge.
