### ISSUE TITLE
Hidden block can break from falling object and drops wrong item

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/Ore-Stages#8]
The block that is hidden is an ore sample, which is configured to drop a chunk of the ore when broken. The ore sample was hidden, and the block it was on fell and caused the ore sample to break, dropping the drop it was configured to drop, rather than the hidden block.

Is this not the same as when a block is broken? Id imagine it is. If so.. I thought in those situations, it would drop the hidden block, and the workaround for when we DIDNT want that to happen was using that new method you provided.

Reference: https://github.com/Darkosto/SevTech-Ages/issues/795

**Comment by darkhax** [comment]
This would be an issue with the ore sample not using the same code as block breaking. Not sure what mod it is, but they would have to fix it on their end.

**Comment by darkhax** [comment]
Looks like this issue was found and it's Base/ContentTweaker
