### ISSUE TITLE
Players can walk in block masking a fence

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/Ore-Stages#9]
Reference: https://github.com/Darkosto/SevTech-Ages/issues/803

**Comment by darkhax** [comment]
This is a known limitation that I told Darkosto about while making the mod. Not sure if this can be reasonably changed by my mod.

**Comment by Darkhax** [comment]
Forge doesn't want to re-implement the events needed for this so it can not be mimicked.
